classDiagram
  direction TB
  namespace cat_harness_tools__workflows {
    class n_cat_harness_tools_workflows_workflow_state["workflow-state: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_tools_workflows_workflow_state" fa_uml_kind_workflow_state
  cssClass "n_cat_harness_tools_workflows_workflow_state" fa_uml_undetermined
