classDiagram
  direction TB
  namespace cat_harness__docs_source {
    class n_cat_harness_docs_source_docs["docs: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_docs_source_docs" fa_uml_kind_docs
  cssClass "n_cat_harness_docs_source_docs" fa_uml_undetermined
