classDiagram
  direction TB
  namespace cat_harness__surveys {
    class n_cat_harness_surveys_session_survey["session-survey: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_cat_harness_surveys_session_survey" fa_uml_kind_session_survey
  cssClass "n_cat_harness_surveys_session_survey" fa_uml_undetermined
