# AGENTS.md — cat-harness

**Cold start, in order.** This file does not restate
[`README.md`](README.md) — that says what this layer *is*, and a description
written twice is a description one copy gets wrong. This says what to **do**,
and it augments rather than replaces the `AGENTS.md` at the root of whatever
checkout includes this layer. The rules that bind everywhere are skills of
this layer, so they are linked here rather than there:
[beans](skills/sdlc/sdlc-core/todo-manager.md),
[the opening brief](skills/sdlc/sdlc-core/opening-brief.md),
[process state](skills/process/workflow/process-state.md),
[continual progress](skills/sdlc/sdlc-core/continual-progress.md),
[context before the question](skills/conduct/conduct-core/interaction-modality.md).

1. **Get the work-plan CLI** — `cat-harness/scripts/install-beans.sh &&
   export PATH="$HOME/.local/bin:$PATH" && beans prime`. A fresh container has
   no `beans`, and the hand-parse fallback cannot claim or create anything.
2. **Claim before you work.** `bun run cat beans:claim <id>` — not
   `beans update --status in-progress`, which writes no holder note. A claim
   announces rather than reserves until your PR exists — see
   `bean-coordination`.
3. **Ask for the skill that governs the task** — `skill_list`, then
   `skill_fetch`. Do not open a path under `skills/` from memory: the graph an
   instance declares is what resolves, and a hardcoded path is how a skill
   goes missing the moment the layout moves.
4. **Say which process you are in**, every turn — the process, the lane, the
   task, and when you switch. `skills/process/workflow/process-state.md`.

## What is specific to THIS layer

> **cat-harness owns the harness; core owns content vocabulary.**
> A schema describing skills, workflows, roles or tools belongs here. One
> describing what a folio HOLDS, where it CAME FROM, or how much of it is
> present belongs in the content layer above this one, which links down to
> here and states the same split from its side.

Three rules that bind here before your first edit, each with its skill as the
text:

- **This is the platform, not a folio.** Subject matter — a chapter, a
  constant, a vocabulary — is either in the wrong repository or belongs in a
  folio as data. A literal naming one folio is the failure this layer exists
  to prevent.
- **A directory is declared or it does not exist.** Add one to
  [`cat-harness.json`](cat-harness.json) with its graph typologies in the same change;
  a declared-but-absent directory makes a consumer scan nothing and report a
  clean run. `kg-core/directory-conventions`.
- **The discipline lives in the skill.** Changing how agents behave means
  editing the skill, not a Markdown file at a root. Where a skill and any
  `AGENTS.md` disagree, **the skill wins and the file is wrong** — fix it.

## Which file answers which question

| you want | read |
|---|---|
| what this layer is, as a reader | [`README.md`](README.md) |
| what to do first, as an agent | this file |
| what the repository is, and every instance in it | the checkout root's `README.md` — not linked, because more than one repository includes this layer. In an index checkout it is **rendered** (`bun run cat index:render`), never hand-written |
| the rules that bind everywhere | the skills linked at the top of this file, and the pointer index below |
| durable facts a subagent owns | `.claude/agent-memory/<agent>/MEMORY.md` — injected, **first 200 lines only** |

That last row is the one distinction worth holding on to: **this file is read,
memory is injected.** Nothing truncates a file, so it carries what an agent
must be able to look up; memory carries what must arrive without being asked
for, and pays a budget for it. Maintaining both is one job —
`conduct-core/agent-memory`.

## Where each rule lives — the pointer index

Moved here 2026-10-09 from the checkout root's `AGENTS.md`, which is now a
rendered file (owner: *"these should be rendrederd files"*). What it carried
that a skill already says was dropped; what follows is the pointer, plus the
facts about THIS layer that no skill states. The original is kept verbatim on
the `fsh-guts` state branch (`separated/root-AGENTS.md`).

### 🛑 Do not edit this file to change how agents work

**`AGENTS.md` is a bootstrap pointer, not the source of truth.** It exists to
get an agent oriented in its first minutes and to send it to the skill that
governs the task in front of it. When you want to change how agents behave,
edit the **skill**. A rule that exists only in an `AGENTS.md` is a rule with no
home: it is not in the generated reference, not in the published skill docs,
and not found by an agent that went looking for the skill first. That has
already happened — the turn-report discipline lived only in the root file until
2026-09-18. Sections that carry substantive rules rather than pointers are
**migration debt**, not precedent; adding to them widens it
([`placement`](skills/kg/kg-core/placement.md),
[the migration's survey](docs/proposals/agents-md-migration.md)).

#### Getting skills

Skills are knowledge-graph content, not a directory you memorise: they live in the `kg` graph an instance declares in its own
`<instance>.json` — here [`cat-harness.json`](cat-harness.json) — and a
downstream instance **inherits** its dependencies' skills through the same
declaration. Ask with `skill_list`, `skill_fetch` and `work_plan_prime`; with
no MCP, resolve the `kg` graph from the declaration
([`kg-navigation`](skills/kg/kg-navigation/kg-navigation.md),
[`directory-conventions`](skills/kg/kg-core/directory-conventions.md)).
**A dependency's skills ARE reachable** — `resolveSkillDirs` in
`schemas/harness-config.ts` computes the cross-instance overlay and
`LOCAL_PACKAGES` in `scripts/skill-packages.ts` is built from it. Two nearby
call sites stay root-only on purpose, and the reasons are on the overlay
function itself: `kgDirectories` composes repo-relative skill ids, and
`kgRoots(root)[0]` is read as the root's graph while overlay order is
deepest-dependency-first.

Start an onboarding at [`docs/guides/agent-onboarding.md`](docs/guides/agent-onboarding.md),
published at
<https://litlfred.github.io/folio-assistant/docs/cat-harness/guides/agent-onboarding.html>.

### Content types, and starting a folio

A **document** folio is structured prose; a **paper** is that plus the block
kinds whose assertion is a formal claim, backed by `.lean` siblings. Adapters
partition and profiles nest — [`content-profiles`](skills/authoring/authoring-core/content-profiles.md).
A new folio is `bun run cat init-folio --help` or the `folio_init` tool, which
is registered among the **generic** tools because it runs before a folio has a
content type; why block manifests import a builder shim rather than the
platform is in [`memory/`](memory/the-builder-shim-and-why-folio-init-is-generic.md),
and the walk-through is [`writing-a-document`](docs/guides/writing-a-document.md).

### Commands, and the gate set

The commands are listed in [`README.md`](README.md#running-it). Two are worth an
agent's attention. **`bun run cat gates` before you push** — it derives its list
from `.github/workflows/code-quality-gates.yml`, and **a subset of the gate set
is not the gate set** ([`platform-gates`](skills/sdlc/sdlc-core/platform-gates.md)).
**`bun run cat preview:site`**, because a green gate set is not a rendered page
([`rendered-verification`](skills/sdlc/sdlc-core/rendered-verification.md), bean `gjli`).

### Where the harness keeps its state — `beans/` is a graph

`beans/` is a graph with named nodes, declared by `beans/beans.json` (schema
`schemas/bean-graph.ts`), and a file declares what it is: a bean by its front
matter, a workflow instance by `"$schema": "folio-workflow-instance/v1"`.
**Extension is a coincidence; a declaration inside the file is the contract.**
The two duplicates of the layout that cannot be removed are both checked by
`bun run cat check:harness-dirs`: `.beans.yml`, because the `beans` binary is
third-party, and `WORKFLOW_DIR` in `src/workflow/store.ts`, because it is on the
hot path of every workflow call. These were `.beans/` and `.harness/workflow/`
until 2026-09-18 (beans `8xzw`, `x89g`), and `.harness/` is gone — a
dot-prefixed path is what this layer's own guard rejects. The tracked graphs
are kept on state branches now and mounted by the session-start hook
(`bun run cat state:mount`). QA verdicts are on the orphan `qa-reports` branch;
judgements stay in `test/attestations/`
([`directory-conventions`](skills/kg/kg-core/directory-conventions.md),
[`workflow-state`](skills/process/workflow/workflow-state.md),
[`qa-reports`](skills/sdlc/sdlc-core/qa-reports.md),
[the proposal](docs/proposals/workflow-state-in-beans.md)).

### Work-plan & todos — use `beans`

One todo mechanism for agent work, session-local and cross-session alike
([`todo-manager`](skills/sdlc/sdlc-core/todo-manager.md),
[`bean-coordination`](skills/sdlc/sdlc-core/bean-coordination.md)). Two
spellings to avoid: `beans <id> --status in-progress` **exits 1 with `unknown
command`**, and `beans update <id> --status in-progress` is not a claim (it
writes no holder note — use `bun run cat beans:claim <id>`). `beans update` stays
right for closing your own bean, `--body-append` and `--blocked-by`. Never
delete a bean — `scrapped`, with reasons — which is one instance of
[`deletion-requires-confirmation`](skills/conduct/conduct-core/deletion-requires-confirmation.md).
Beans are not sidecars, and this is not the content-review feedback workflow
([`todo-review`](skills/authoring/authoring-core/todo-review.md)).

### At session start

Get `beans` in hand before any durable work (step 1 above). If it will not
install you are still not read-only: `scripts/beans-fallback.ts` writes the same
store in the same layout. The session-start sweep
(`scripts/session-start-coord-sweep.sh`) prints a copy-paste line for resuming;
set `BEANS_CHECKOUT_ROOT` if your clones live under one predictable directory
and it will name the path there. What the sweep emits, and in what order, is
[`todo-manager`](skills/sdlc/sdlc-core/todo-manager.md).

### README sections

The folio owns the file; the platform owns the markers.
[`readme-sections`](skills/ui/ui-core/readme-sections.md) is the full
post-mortem — the opt-in contract, the third state, why every link is resolved
rather than composed, and the whole-file generator it replaced. The root
`README.md` of an index checkout is the one README the platform owns outright:
`bun run cat index:render` writes it, with the root `AGENTS.md`, `CLAUDE.md` and
`GEMINI.md`, and `index:render:check` gates it.

### Boards, windows and harness tiles

A board is a diagram OF a folio; the arrow runs `folio → board → position →
note` and never back
([`board-diagram-interchange`](skills/ui/ui-core/board-diagram-interchange.md),
[`board-windows`](skills/ui/ui-core/board-windows.md),
[`harness-tiles`](skills/ui/ui-core/harness-tiles.md)). Their processes are
executable diagrams in the content layer's `processes/ui/`.

### CI health, repository health and audit coverage

Three questions, three commands. **`bun run cat check:ci-health`** — do the
workflows pass, and are the Pages previews building
([`ci-health`](skills/sdlc/sdlc-core/ci-health.md); one workflow failed all 30
times over two months with nothing saying so, bean `xom7`). Do not "fix" a
dispatch-only workflow by dispatching it
([`memory/`](memory/two-workflows-fail-by-design-here-do-not-fix-them-by-dispatc.md)).
**`bun run cat health`** — the repository itself: how much of the publish branch
the previews occupy, what a clone costs, whether the work plan has duplicates or
unhonoured claims. Its checks are in `test/health/`, `health:list` names them,
and every threshold carries its **basis**. The same three rules as CI health
hold — could-not-determine is never clean, the tracking issue is edited in
place, and on `unknown` it is left untouched while the job fails — and **it
reports and never acts**: every finding's action is a person's
([`deletion-requires-confirmation`](skills/conduct/conduct-core/deletion-requires-confirmation.md),
bean `plj1`). **`bun run cat audit:coverage`** — what is audited at all, per
graph typology ([`audit-coverage`](skills/kg/kg-core/audit-coverage.md)).

### Actors, roles and skills — a role is a swimlane

> **An actor performs a task in a process as a role, using that role's skills.**

Nothing *is* a reviewer; somebody acts as one for the duration of a lane
([`role-model`](skills/process/process-core/role-model.md)). The audit is
`bun run cat kg:audit`.

### Subagents with persistent memory

`.claude/agents/` declares subagents with `memory: project`; each gets a
`MEMORY.md` of which the **first 200 lines** are injected. Entries are authored
as nodes under a declared `memory/` directory, and maintaining them is part of
the work ([`agent-memory`](skills/conduct/conduct-core/agent-memory.md)).

### Feature requests and CRDM

A feature request enters the CRDM requirements workflow rather than being
implemented directly ([`crdm-detect`](skills/sdlc/crdm/crdm-detect.md),
[`crdm-requirements-workflow`](skills/sdlc/crdm/crdm-requirements-workflow.md),
[the methodology](docs/process/crdm-methodology.md)). **The process is
executable — do not hand-roll a phase tracker**: `workflow_start` /
`workflow_next` / `workflow_complete` run it, and `crdm_start` / `crdm_status`
should not be built. The interaction model as a whole is
[the agentic harness page](docs/concepts/agentic-harness.md).

### Say which process you are in, working an issue, and committing

- **Say which process you are in, every turn**, and when you switch — and the
  committed workflow instance is the evidence
  ([`process-state`](skills/process/workflow/process-state.md)).
- **Working an issue**: announce the branch when you create it, and re-check
  the issue for new *and edited* comments while you work
  ([`issue-working`](skills/sdlc/sdlc-core/issue-working.md)).
- **Commit early, commit often, always PR** (STRICT) — open the PR at the first
  commit, and do not hold a green PR back
  ([`continual-progress`](skills/sdlc/sdlc-core/continual-progress.md)). A folio
  may be stricter, and it wins.

### Context before the question (STRICT)

**Order: context → options → recommendation → question.** Can the reader answer
without opening anything?
([`interaction-modality`](skills/conduct/conduct-core/interaction-modality.md) §4.1,
[`turn-reporting`](skills/sdlc/sdlc-core/turn-reporting.md)).

### Opening a bean or a topic — brief it before you touch anything (STRICT)

Before the first tool call: what and why, what you already know and its
provenance, how you will do it and what would falsify it, and what you are not
doing ([`opening-brief`](skills/sdlc/sdlc-core/opening-brief.md)).

### More

- **Not sure where a thing goes?** [`where-does-this-go`](skills/conduct/conduct-core/where-does-this-go.md),
  and its companion [`surprise-to-corpus`](skills/kg/kg-core/surprise-to-corpus.md).
- **`uses[]` and `interprets` are the EDITORIAL relation** — never populate
  `uses[]` from Lean. Contract: `BlockBase.uses` and `RemarkBlock.interprets` in
  `schemas/types.ts` ([`uses-editorial-review`](skills/authoring/authoring-core/uses-editorial-review.md)).
- **Every process is BPMN, and the diagrams are executable**
  ([`bpmn-processes`](skills/process/workflow/bpmn-processes.md),
  [`workflow-state`](skills/process/workflow/workflow-state.md),
  [the publication-workflow page](docs/process/publication-workflow.md)).
  `bun run cat render:bpmn` regenerates the pictures.
- **Process state, blocking and swarms** —
  [`process-state`](skills/process/workflow/process-state.md),
  [`bean-blocking`](skills/sdlc/sdlc-core/bean-blocking.md),
  [`swarm-management`](skills/sdlc/sdlc-core/swarm-management.md).
- **An instance declares the directories it scans** in `<instance>.json`, each
  with the kind of graph it holds; overrides match on the entry's `id`, not its
  `path`, and only what exists is declared
  ([`content-context-and-state-graphs`](skills/kg/kg-core/content-context-and-state-graphs.md),
  [`directory-conventions`](skills/kg/kg-core/directory-conventions.md)).
  `cat-harness.json` is the list — not a sentence anywhere.
- **Adding a skill is never a one-file change** — `bun run cat skill:register`
  ([`skill-registration`](skills/kg/kg-core/skill-registration.md)).
- **Shipping a branch** — [`prepare-merge`](skills/sdlc/sdlc-core/prepare-merge.md);
  **watching a sibling PR** — [`watch`](skills/sdlc/sdlc-core/watch.md).
- **Migration plan and cross-repo coordination** —
  [`docs/folio-assistant-migration.md`](docs/folio-assistant-migration.md); the
  Lean tooling roadmap is issue #198.
- **The generated references are never hand-edited**: regenerate them with
  `bun run cat-harness/scripts/gen-schema-docs.ts` and
  `bun run cat-harness/scripts/gen-skill-docs.ts`.

---

*A declared asset of this instance ([`cat-harness.json`](cat-harness.json), role
`agent-instructions`). Authored here — it is not a copy of
[`bootstrap/AGENTS.md`](../bootstrap/AGENTS.md). The checkout root's
`AGENTS.md` quotes that file as its cold start, and is rendered rather than
declared (`scripts/index-render.ts`). Issue #592.*
