classDiagram
  direction TB
  namespace folio_assistant_core__beans {
    class n_folio_assistant_core_beans_beans["beans: no node schema"] {
      <<could not determine>>
    }
  }
  cssClass "n_folio_assistant_core_beans_beans" fa_uml_kind_beans
  cssClass "n_folio_assistant_core_beans_beans" fa_uml_undetermined
