classDiagram
  direction TB
  namespace folio_assistant_core__defs {
    class folio_assistant_core_defs_BeanKind["BeanKind"] {
      <<json: BeanKind>>
      id [0..1] string
      title [0..1] string
      status [0..1] string
      type [0..1] string
      priority [0..1] string
      parent [0..1] string
      blocking [0..*] string[]
      blocked_by [0..*] string[]
      created_at [0..1] string
      updated_at [0..1] string
      tags [0..*] string[]
      issue [0..1] integer | string
      targets [0..1] string[] | string
      $schema [1] string
    }
  }
  cssClass "folio_assistant_core_defs_BeanKind" fa_uml_kind_bean_defs
